---
title: "Data Management Planning"
---

## What Are Data Management Plans (DMPs) and Why Should You Care?

A Data Management Plan (DMP) is a strategic document that outlines how you will handle data throughout the life cycle of a project. It serves as a roadmap for managing, storing, and sharing data effectively, ensuring that your data is well-organized, accessible, and secure. By documenting your data management strategies, a DMP helps streamline data workflows, facilitates compliance with institutional and funding agency requirements, and enhances the efficiency and integrity of research.

The importance of a DMP can be highlighted in several ways:

1.  *Organization and efficiency:* A well-structured DMP ensures that data is collected, stored, and analyzed in a consistent and organized manner. This reduces the risk of data loss, duplication, or mismanagement, and helps team members quickly find and use the data they need.

2.  *Resource allocation:* The plan helps allocate resources effectively, including budgeting for data management tools and personnel. This foresight can prevent unexpected costs and ensure that data management tasks are adequately resourced.

3.  *Data security and privacy:* The DMP outlines measures for safeguarding sensitive or confidential data, ensuring compliance with privacy regulations and ethical guidelines. This includes specifying access controls, encryption methods, and protocols for data anonymization.

4.  *Data sharing and reproducibility:* By detailing how data will be shared and made available, the DMP supports transparency and collaboration. This includes specifying data formats, metadata standards, and repositories for public or restricted access, which enhances the reproducibility of research findings.

5.  *Long-Term preservation:* The DMP addresses strategies for long-term data preservation, including backup procedures, archival formats, and storage solutions. This ensures that valuable data remains accessible and usable beyond the immediate project duration.

Most funders require researchers to submit a Data Management Plan (DMP) along with their research proposal as a prerequisite for consideration. However, developing a DMP offers substantial benefits beyond meeting this requirement. It serves as a crucial tool for all researchers, aiding them in anticipating resource needs, exploring available services, and strategically planning for data management throughout the project's life cycle. For example, a researcher planning to conduct interviews can use the DMP to identify and utilize institutionally-supported transcription services and secure storage solutions.

By anticipating these needs early on, the researcher can allocate appropriate budget and resources, ensuring that these essential services are available when required. Additionally, the DMP helps the researcher create a structured plan for managing qualitative data, such as organizing interview transcripts, coding data, and maintaining a detailed audit trail of data analysis decisions.

Broadly, the DMP should cover the following topics:

1.  The types of data you expect to collect,

2.  How those data will be documented and organized,

3.  How the data will be stored and kept secure, and

4.  How the data will be shared (or why not) and stored for the long term.

The ultimate goal is that researchers will make more informed decisions on how to produce and share data satisfying the FAIR principles:


<iframe width="50%" height="700" src="https://rcd.ucsb.edu/sites/default/files/2023-03/dls-n04-2021-fair-navy.pdf">

</iframe>

Source: UCSB Library Data Literacy Series ([perma.cc/U4D8-UYFR](https://perma.cc/CT8P-D5MK)).


Researchers studying indigenous communities should pay special attention to an additional set of principles, named CARE, an acronym for a set of purpose-oriented principles for Indigenous Data Governance, which aims to help advancing Indigenous innovation, sovereignty, and self-determination.

<iframe width="50%" height="700" src="https://rcd.ucsb.edu/sites/default/files/2023-02/dls-n1-2022-careprinciples-navy.pdf">

</iframe>

Source: UCSB Library Data Literacy Series ([perma.cc/U4D8-UYFR]https://perma.cc/3ZHR-6JAG)).


## Crafting a DMP for Qualitative Research

Fortunately, creating a DMP is simplified with the help of appropriate templates.The DMPTool is an excellent resource for researchers to develop customized data management plans tailored to specific disciplines and funding agencies. To get started with the DMPTool, follow these steps:

1.  Visit [DMPTool](https://dmptool.org/) in your web browser.

2.  On the DMPTool homepage, enter your .utexas.edu email address on the right side and click "Continue."

3.  The tool will automatically recognize your affiliation. Click the "Sign in with Institution (SSO)" button to be redirected to the EID sign-in page and complete the sign-in process.

The DMPTool offers a wide range of templates tailored to specific funder requirements and assists you in structuring your Data Management Plan (DMP) according to these templates. It guides you through the process with targeted questions, ensuring that all necessary components are addressed. Once completed, the tool generates a well-organized and professionally formatted DMP.

The Qualitative Data Repository (QDR) has developed a specialized [data management checklist](https://qdr.syr.edu/drupal_data/public/QDR%20-%20Data%20Management%20Checklist.pdf) for qualitative researchers to ensure that their Data Management Plans (DMPs) address all critical aspects. The checklist includes topic-specific examples from qualitative research where applicable, and offers practical tips based on our extensive experience advising researchers on their DMPs. You can use this checklist proactively as a guide while drafting your DMP, or as a tool to review and confirm that an existing DMP comprehensively covers all necessary elements. Using the DMPTool in tandem with QDR’s checklist can provide additional clarity and help you navigate the various topics effectively. This combination ensures that your DMP is comprehensive, meets all requirements, and is easy to understand.

For future reference, you may find valuable insights by consulting the list of the [11 winning DMPs](https://blog.dmptool.org/2021/05/19/dmp-competition-winners-dmps-so-good-they-go-to-11) from the DMPTool Qualitative Data Competition. These exemplary DMPs showcase best practices and innovative approaches in managing qualitative data, offering a useful benchmark for developing your own plan.

## Update as You Progress

DMPs aren't meant to collect dust; they should be treated as living documents that evolve alongside your project. To ensure they stay relevant and accurate, it's crucial to implement version control. Regularly update the DMP to reflect any changes in your project, and track these revisions to maintain a clear history of modifications. This way, you can easily reference past versions, understand the evolution of your project, and ensure that everyone involved is working with the most current information.

Ethical considerations are paramount in any research, but they take on added significance in qualitative research, where interactions and data collection are often more personal and complex. It’s vital to address these considerations early in the research process and incorporate them into the Data Management Plan (DMP). For qualitative research, the DMP should be particularly detailed in outlining these ethical aspects. This includes obtaining informed consent from participants, ensuring confidentiality and privacy, managing potential biases, and being transparent about how data will be used. By embedding these considerations into a well-defined DMP, you create a framework that not only supports responsible and respectful research practices but also anticipates the resources and services needed for compliance. In the next episode, we will explore the ethical dimensions of qualitative research in greater detail.
------------------------------------------------------------------------

**Recommended/Cited Sources:**

Qualitative Data Repository (2017). *Data Management Checklist*. <https://qdr.syr.edu/drupal_data/public/QDR%20-%20Data%20Management%20Checklist.pdf>
