---
title: "Sharing and Archiving Qualitative Data"
editor: 
  markdown: 
    wrap: 72
---

-   Before sharing the files:
    <https://managing-qualitative-data.org/modules/3/b/> (types of
    access controls)

-   When possible, consider sharing de-identified transcripts openly,
    while placing recordings under more stringent access controls.

-   Do keep a list of de-identification rules, both for yourself, or for
    your team should you collaborate. This list serves as important
    documentation when you share your data. See for example the protocol
    used by Thad Dunning and Edward Camp to de-identify data deposited
    with the Qualitative Data Repository. This document is separate from
    the key that links de-identified entries to the actual individuals
    or entities interviewed, which should not be included when you share
    your data.

-   Do check the document properties of files, which may contain
    identifiers such as original file names identifying interview
    respondents.

-   Finally, do try to strike a balance between keeping your
    participants’ information confidential and unnecessarily reducing
    the analytic value of the data by removing too much information. If
    you are having difficulties striking that balance, you could ask
    another subject-matter expert for assistance; some repository
    personnel or data librarians can also provide abstract rules that
    you can follow.

## Epistemological Tensions With Sharing Qualitative Data

## Ethical Issues to Address When Sharing Qualitative Data

<https://journals.sagepub.com/doi/10.1177/25152459231205832>

Reasons for sharing -

<https://psycnet.apa.org/fulltext/2017-12030-001.html> Add Table 1:
Materials that are common;y archived

Levels of sharing:

documentation and metadata (codebook only) -
<https://datadryad.org/stash/dataset/doi:10.5061/dryad.z612jm6hw>

restricted:

all:
<https://researchportal.bath.ac.uk/en/studentTheses/the-lived-experiences-of-relapse-into-opiate-and-crack-cocaine-mi>

Data needs documentation:

Bad example:
<https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/4C9KFK/XRREIY&version=1.1>

Much Better Example:
<https://researchportal.bath.ac.uk/en/studentTheses/the-lived-experiences-of-relapse-into-opiate-and-crack-cocaine-mi>

## What data?

ICPSR's Guide for Sharing Qualitative Data outlines examples of of
qualitative data sources that may be archived for secondary analysis:

• Interview methods, including those captured through notes, audio, and
video

-   In-depth and/or unstructured interviews

-   Semi-structured interviews

-   Focus group interviews

• Diary studies that are unstructured or use semi-structured writing
prompts

• Observational studies that generate field notes and other text and
information

-   Naturalistic observation of real-world environments (e.g.,
    classrooms, workplaces, healthcare facilities, courtrooms, public
    spaces)

-   Participant observation where the researcher becomes an active part
    of the setting to collect information (e.g., online gaming,
    community policing, nightclub culture)

-   Structured observation is where the research has predefined
    objectives and a systemic approach to collecting information. This
    would include case studies.

• Text from available sources

-   Meeting minutes

-   Official records Medical records

-   News sources and social media

-   Excerpts of copyrighted materials (e.g., literature, film, music)

• Survey methods or questionnaires with substantial open-ended comments

## Where you should share your Data

## Preparing your data for Submission

### Documenting your Data

Required:

-   Original source data, when possible, and as long as it is
    de-identified

-   Processed data (e.g., transcripts)

-   Codebook

-   Readme

-   Instrument for data collection (e.g., survey, interview, etc), if
    applicable

-   Documentation generated in the Qualitative Data Analysis Software
    (QDAS) application: memos, notes, networks, classifications

Recommended:

-   Informed consent statement(s) or assent (see the Human Subjects Data
    Essentials Primer)

-   IRB protocol (see the Human Subjects Data Essentials Primer)

-   Study protocol or procedures manual

-   Data Management Plan --To indicate how long the data needs to be
    preserved/accessible, and any other stipulations on
    sharing/management.

<iframe width="50%" height="800" src="https://rcd.ucsb.edu/sites/default/files/2024-07/DLS-202407-QualDataSharing.pdf">

</iframe>

\<iframe width="50%" height="800"
src="https://rcd.ucsb.edu/sites/default/files/2024-02/DLS-202402-DataAvailability_navy.pdf"\>
</iframe>"

Project example:
<https://rdr.ucl.ac.uk/articles/dataset/Qualitative_and_output_data_on_loneliness_among_young_adults/17212991/1>

Data Availability Statements

<https://rcd.ucsb.edu/sites/default/files/2024-02/DLS-202402-DataAvailability_navy.pdf>
