---
title: "Documenting Data"
editor: visual
---

## What should you document?

When conducting qualitative research, it's crucial to maintain thorough documentation to ensure transparency and ethical compliance. Documentation should include both project and file level documentation. Here’s what we should recommend Sarah to document and preserve:

**FIXME: re-org strucutre - link with the sharing and archiving ep. (not everything needs to be shared!)**

**Required**

1.  Original Source Data: Retain the original data whenever possible, ensuring it is de-identified to protect participant privacy.

2.  Processed Data: Include finalized versions of your data, such as transcripts of interviews or focus groups.

3.  Readme File: an overview of your project, including data sources, their relationships and a brief description of the methods.

4.  Data Collection Instruments: A sample of instruments used for data collection, such as surveys or interview guides.

5.  Codebook: the coding framework used, including definitions of codes and categories.

6.  Documentation from Qualitative Data Analysis Software (QDAS): Include all relevant materials generated from QDAS tools (e.g., NVivo, Atlas.ti), such as memos, notes, network diagrams, and classifications.

7.  Informed Consent/Assent Statements: copies of informed consent or assent documents, following the guidelines.

8.  IRB Protocol: a copy of the Institutional Review Board (IRB) protocol.

9.  Study Protocol or Procedures Manual: a comprehensive guide outlining the study procedures and methodology.

10. Data Management Plan: specifying how long the data will be preserved and any stipulations regarding its sharing and management.

    ::: callout-important
    ## REFI-QDA Codebook (Items 5 & 6)

    As seen, a codebook in qualitative or mixed-methods research is a structured list of defined keywords or phrases that represent key themes, concepts, or topics of interest to the researcher. These keywords or phrases are commonly referred to as "codes."

    In qualitative data analysis (QDA) software, codes can be linked to specific segments of data where they appear. While the codebook serves as a comprehensive listing of codes, many QDA programs also allow for the organization of these codes in various ways, depending on the features of the software used.

    The REFI-QDA Standard enables interoperability between Qualitative Data Analysis Software (QDAS or CAQDAS) programmes. It ensures that a codebook developed in one of the compatible software programs can be exported and imported into any other listed programs, including QualCoder, which complies with this format.

    It’s important to note that because each program has unique functionalities regarding codes and their organization, users may encounter some modifications when importing a codebook into a different software environment.

    Check which QDA software are REFI-QDA compatible: <https://www.qdasoftware.org/refi-qda-codebook>
    :::

By adhering to this documentation checklist, researchers can enhance the credibility and ethical integrity of their qualitative data projects.
