---
title: "Reusing Qualitative Human Subject Data"
---

Sharing well-documented data and connecting it to related research is crucial for maximizing reuse potential. With the tips we've provided and the support of QualCoder for exporting codebooks and reports, Sarah can easily share her project with the research community. This ensures that her work is valuable within her field and accessible to other disciplines. By adopting this approach, she enhances the reuse value of her data and fosters collaboration across various research areas!

Research data can be reused in various ways, as outlined in the handout below:

<iframe width="50%" height="800" src="https://rcd.ucsb.edu/sites/default/files/2023-03/dls-n06-2021-reuse-navy.pdf">

</iframe>

Source: UCSB Library Data Literacy Series ([perma.cc/U4D8-UYFR](https://perma.cc/AD4C-272F){target='_blank'}).

The [UK Data Archive](https://ukdataservice.ac.uk/learning-hub/qualitative-data/reusing-qualitative-data/approaches-to-reusing-qualitative-data){target='_blank'} highlights more specific applications of qualitative data secondary analysis:

-   *Description:* Previous research can be utilized to describe the attributes, attitudes, and behaviors of individuals, societies, groups, or organizations during the original project period.

-   *Comparative Research:* This approach enables comparisons over time or among different social groups or regions.

-   *Reanalysis:* Involves posing new questions to the data and interpreting it in ways not addressed by the original researchers. This could include exploring different themes or topics. The richness and contextual detail of the raw data enhance the potential for fresh insights, without attempting to undermine previous analyses.

-   *Research Design and Methodological Advancement:* This approach focuses on designing new studies or developing methodologies and research tools. Researchers can gain valuable insights by examining sampling methods, data collection strategies, and topic guides. While researchers often publish sections on methods, their fieldwork diaries and analytic notes can provide deeper context about the research's development.

-   *Learning and Teaching:* Both classic and contemporary studies serve as valuable case materials for teaching research methods and substantive topics across various social science disciplines.

When considering various approaches to data reuse, researchers should ask the following questions:

-   What are the purposes of reuse?

-   Do you fully understand the licenses or any restrictions applied to your data of interest?

-   Are the new questions similar to or significantly different from those posed by the original researchers?

-   Do you fully understand the study's limitations?

Some of these answers will also help to inform a Data Request for controlled access data.

### **Responsibilities**

We have talked about the responsibilities of researchers sharing data, but what are the responsibilities of those reusing pre-existing research data?

Researchers interested in reusing QHS data need to pay special attention to the following:

1\. Proper Attribution: Acknowledge the original creators of the data by giving them credit, thereby respecting their contributions and intellectual property rights.

2\. Compliance with Licensing: Familiarize yourself with and follow the terms of any licenses associated with the data, ensuring your usage aligns with the specified conditions.

3\. Verification of Data Quality: Evaluate the reliability and quality of the data before using it to ensure it meets your intended purpose.

4\. Transparency in Use: Document how you used the data, including any modifications, to maintain transparency and facilitate replicability.

5\. Ethical Considerations: Be aware of ethical issues, such as privacy concerns and potential biases in the data, and take measures to address any negative impacts.

6\. Data Security: Safeguard the data, especially if it contains sensitive information, to prevent unauthorized access or misuse.

7\. Sharing Findings: Share your results and insights about utilizing the data, contributing to the community and promoting further research.

### Citation & Attribution

Data citation and attribution are vital, especially when it comes to recognizing the hard work of researchers like Sarah in her digital influencers project. Since she invested significant effort in gathering and analyzing her data, it's essential that she receives proper attribution to acknowledge her contributions to the topic. This not only upholds academic integrity but also enhances the credibility and visibility of her research.

The good news is that most data repositories offer a recommended citation alongside a persistent identifier, such as a DOI, simplifying referencing datasets. If a citation is not available, we recommend following the guidelines outlined in this handout:

<iframe width="50%" height="800" src="https://rcd.ucsb.edu/sites/default/files/2023-03/dls_n2_datacitation_navy_1.pdf">
</iframe>


Source: UCSB Library Data Literacy Series ([perma.cc/VHW9-9EPQ](https://perma.cc/VHW9-9EPQ){target='_blank'})
