---
title: "Handling and Sharing Qualitative Data Responsibly and Effectively"
author:
  - name: Renata Curty
    url: https://www.library.ucsb.edu/staff/renata-curty
    orcid: 0000-0002-4615-6030
  - name: Julien Brun
    url: https://brunj7.github.io/
    orcid: 0000-0002-7751-6238
  - name: Greg Janée
    url: https://www.library.ucsb.edu/staff/greg-janee
    orcid: 0000-0001-8785-0021
date: last-modified
citation: 
  url: https://ucsb-library-research-data-services.github.io/change
categories: [data ethics, data management, data de-identification, human subjects, qualcoder, qualitative research, sensitive data, thematic analysis]
---

## Course Description

Qualitative data is vital in social sciences research as it delves deep into human behavior, attitudes, and interactions, offering a comprehensive perspective beyond what quantitative data can provide. It can offer valuable insights into the intricacies of social relationships and as means to develop hypotheses, theories, and models, guiding further inquiry and contributing to knowledge advancement. Often times qualitative data derives from researchers recruitment and engagement with human subjects posing additional challenges and considerations for proper data management.

This website aims to assist researchers to better and ethically manage qualitative data from studies involving human subjects throughout its life cycle, since planning to sharing and reusing. Episodes were developed in such way to help researchers:

-   Understand the nuances and challenges of working with qualitative data;

-   Learn about the ethical aspects around working with human subjects data and how to stay compliant with IRB regulations;

-   Craft better consent forms to allow for data sharing and reuse;

-   Select and apply data de-identification techniques;

-   Get started with tools to manage and analyze qualitative data;

-   Identify best approaches to share and receive credit for qualitative data.

This course is grounded in the research data life cycle depicted in the graphical handout below which focuses on approaches for researchers to handle human subject qualitative data more effectively & responsibly. We will use this framework to explore recommended data management practices applied to human subjects qualitative data throughout the following steps: 1) planning and collecting, 2) analyzing and documenting, 3) sharing/archiving, and 4) reusing.

<iframe width="50%" height="800" src="https://rcd.ucsb.edu/sites/default/files/2024-04/DLS-202403-ManagingHS-QualData-navy.pdf">

</iframe>

Source: UCSB Library Data Literacy Series. Click to expand: ([perma.cc/D95L-54W8](https://perma.cc/D95L-54W8){target='_blank'}).

Researchers and students are welcome to take advantage of this learning resource asynchronously at their own pace. We also encourage faculty to reuse or repurpose content to their research methods classes. If you'd like to us to host a hands-on in-person or remote workshop for your team, reach out to RDS for scheduling: [rds\@library.ucsb.edu](mailto:rds@library.ucsb.edu){.email}.
